"""add kb config columns

Revision ID: 0b2d7d870f87
Revises: a1b2c3d4e5f6
Create Date: 2026-06-25 22:53:08.620169
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers
revision: str = '0b2d7d870f87'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('evaluation_results')
    # op.drop_table('evaluation_datasets')
    op.drop_table('evaluation_runs')
    op.add_column('knowledge_bases', sa.Column('embedding_model', sa.String(length=100), nullable=True))
    op.add_column('knowledge_bases', sa.Column('chunking_strategy', sa.String(length=50), nullable=True))
    op.add_column('knowledge_bases', sa.Column('chunk_size', sa.Integer(), nullable=True))
    op.add_column('knowledge_bases', sa.Column('chunk_overlap', sa.Integer(), nullable=True))
    op.add_column('knowledge_bases', sa.Column('retrieval_strategy', sa.String(length=50), nullable=True))
    op.add_column('knowledge_bases', sa.Column('rerank_model', sa.String(length=100), nullable=True))
    op.add_column('knowledge_bases', sa.Column('rerank_top_n', sa.Integer(), nullable=True))
    op.add_column('knowledge_bases', sa.Column('graphrag_indexed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('knowledge_bases', 'graphrag_indexed')
    op.drop_column('knowledge_bases', 'rerank_top_n')
    op.drop_column('knowledge_bases', 'rerank_model')
    op.drop_column('knowledge_bases', 'retrieval_strategy')
    op.drop_column('knowledge_bases', 'chunk_overlap')
    op.drop_column('knowledge_bases', 'chunk_size')
    op.drop_column('knowledge_bases', 'chunking_strategy')
    op.drop_column('knowledge_bases', 'embedding_model')
    op.create_table('evaluation_runs',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('dataset_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('progress', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_tasks', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('completed_tasks', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('summary', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('resume_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('last_resumed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('report_json_path', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('report_md_path', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='evaluation_runs_created_by_fkey'),
    sa.ForeignKeyConstraint(['dataset_id'], ['evaluation_datasets.id'], name='evaluation_runs_dataset_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='evaluation_runs_pkey'),
    postgresql_ignore_search_path=False
    )
    # op.create_table('evaluation_datasets',
    # sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    # sa.Column('name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    # sa.Column('kb_id', sa.INTEGER(), autoincrement=False, nullable=True),
    # sa.Column('qa_pairs', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    # sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    # sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    # sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=True),
    # sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='evaluation_datasets_created_by_fkey'),
    # sa.ForeignKeyConstraint(['kb_id'], ['knowledge_bases.id'], name='evaluation_datasets_kb_id_fkey', ondelete='CASCADE'),
    # sa.PrimaryKeyConstraint('id', name='evaluation_datasets_pkey'),
    # postgresql_ignore_search_path=False
    # )
    op.create_table('evaluation_results',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('run_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('qa_index', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('question', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('ground_truth', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('embedding_model', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('retrieval_strategy', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('rerank_model', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('generation_model', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('retrieved_chunks', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('generated_answer', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('retrieval_metrics', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('generation_scores', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('ragas_scores', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('latency_ms', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('judge_error', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('ragas_error', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['evaluation_runs.id'], name='evaluation_results_run_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='evaluation_results_pkey'),
    sa.UniqueConstraint('run_id', 'qa_index', 'embedding_model', 'retrieval_strategy', 'rerank_model', 'generation_model', name='uq_eval_result')
    )
    # ### end Alembic commands ###
