"""add agent column to messages

Revision ID: 891d6d4d7375
Revises: a8f8f6e68df2
Create Date: 2026-06-13 12:19:55.907397
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers
revision: str = '891d6d4d7375'
down_revision: Union[str, None] = 'a8f8f6e68df2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('agent', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'agent')
    # ### end Alembic commands ###
